# Generated by Django 4.2.4 on 2024-05-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_aluno",
                    models.CharField(max_length=100, verbose_name="Nome do Aluno"),
                ),
                (
                    "nome_mae",
                    models.CharField(max_length=100, verbose_name="Nome da Mãe"),
                ),
                (
                    "cpf_mae",
                    models.CharField(max_length=100, verbose_name="CPF da Mãe"),
                ),
                (
                    "nome_pai",
                    models.CharField(max_length=100, verbose_name="Nome do Pai"),
                ),
                (
                    "cpf_pai",
                    models.CharField(max_length=100, verbose_name="CPF do Pai"),
                ),
                ("endereco", models.CharField(max_length=100, verbose_name="Endereço")),
                ("telefone", models.CharField(max_length=100, verbose_name="Telefone")),
                ("dt_inicio", models.DateField()),
                (
                    "mensalidade",
                    models.CharField(max_length=100, verbose_name="Mensalidade"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateField(null=True)),
            ],
            options={
                "ordering": ["nome_aluno"],
            },
        ),
    ]
